// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZJAdmin.Api.Data;

#nullable disable

namespace ZJAdmin.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("ZJAdmin.Api.Models.Config", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigKey")
                        .IsUnique();

                    b.ToTable("sys_config");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ConfigKey = "site_title",
                            ConfigValue = "ZJAdmin 最简后台",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "网站标题"
                        },
                        new
                        {
                            Id = 2L,
                            ConfigKey = "site_keywords",
                            ConfigValue = "ZJAdmin,最简后台,后台管理,RBAC",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "网站关键词"
                        },
                        new
                        {
                            Id = 3L,
                            ConfigKey = "site_icp",
                            ConfigValue = "",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "备案信息"
                        },
                        new
                        {
                            Id = 4L,
                            ConfigKey = "site_copyright",
                            ConfigValue = "Copyright © 2026 ZJAdmin. All rights reserved.",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "版权信息"
                        });
                });

            modelBuilder.Entity("ZJAdmin.Api.Models.ExceptionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestParams")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("sys_exception_log");
                });

            modelBuilder.Entity("ZJAdmin.Api.Models.OperationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Module")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OperationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationType")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestParams")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseResult")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("sys_operation_log");
                });

            modelBuilder.Entity("ZJAdmin.Api.Models.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Component")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sort")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Visible")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("sys_permission");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "system",
                            Component = "Layout",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "Setting",
                            Name = "系统管理",
                            ParentId = 0L,
                            Path = "/system",
                            Sort = 1,
                            Type = (byte)0,
                            Visible = (byte)1
                        },
                        new
                        {
                            Id = 2L,
                            Code = "system:user",
                            Component = "system/user/index",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "User",
                            Name = "用户管理",
                            ParentId = 1L,
                            Path = "/system/users",
                            Sort = 1,
                            Type = (byte)0,
                            Visible = (byte)1
                        },
                        new
                        {
                            Id = 3L,
                            Code = "system:role",
                            Component = "system/role/index",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "Avatar",
                            Name = "角色管理",
                            ParentId = 1L,
                            Path = "/system/roles",
                            Sort = 2,
                            Type = (byte)0,
                            Visible = (byte)1
                        },
                        new
                        {
                            Id = 4L,
                            Code = "system:permission",
                            Component = "system/permission/index",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "Lock",
                            Name = "权限管理",
                            ParentId = 1L,
                            Path = "/system/permissions",
                            Sort = 3,
                            Type = (byte)0,
                            Visible = (byte)1
                        },
                        new
                        {
                            Id = 5L,
                            Code = "logs",
                            Component = "Layout",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "Document",
                            Name = "日志管理",
                            ParentId = 0L,
                            Path = "/logs",
                            Sort = 2,
                            Type = (byte)0,
                            Visible = (byte)1
                        },
                        new
                        {
                            Id = 6L,
                            Code = "logs:operation",
                            Component = "logs/operation/index",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "Edit",
                            Name = "操作日志",
                            ParentId = 5L,
                            Path = "/logs/operation",
                            Sort = 1,
                            Type = (byte)0,
                            Visible = (byte)1
                        },
                        new
                        {
                            Id = 7L,
                            Code = "logs:exception",
                            Component = "logs/exception/index",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "Warning",
                            Name = "异常日志",
                            ParentId = 5L,
                            Path = "/logs/exception",
                            Sort = 2,
                            Type = (byte)0,
                            Visible = (byte)1
                        },
                        new
                        {
                            Id = 8L,
                            Code = "dashboard",
                            Component = "dashboard/index",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "HomeFilled",
                            Name = "首页",
                            ParentId = 0L,
                            Path = "/dashboard",
                            Sort = 0,
                            Type = (byte)0,
                            Visible = (byte)1
                        },
                        new
                        {
                            Id = 9L,
                            Code = "system:user:query",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查询用户",
                            ParentId = 2L,
                            Sort = 0,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 10L,
                            Code = "system:user:add",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "新增用户",
                            ParentId = 2L,
                            Sort = 1,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 11L,
                            Code = "system:user:edit",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "编辑用户",
                            ParentId = 2L,
                            Sort = 2,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 12L,
                            Code = "system:user:delete",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "删除用户",
                            ParentId = 2L,
                            Sort = 3,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 13L,
                            Code = "system:role:query",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查询角色",
                            ParentId = 3L,
                            Sort = 0,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 14L,
                            Code = "system:role:add",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "新增角色",
                            ParentId = 3L,
                            Sort = 1,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 15L,
                            Code = "system:role:edit",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "编辑角色",
                            ParentId = 3L,
                            Sort = 2,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 16L,
                            Code = "system:role:delete",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "删除角色",
                            ParentId = 3L,
                            Sort = 3,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 17L,
                            Code = "system:permission:query",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查询权限",
                            ParentId = 4L,
                            Sort = 0,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 18L,
                            Code = "system:permission:add",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "新增权限",
                            ParentId = 4L,
                            Sort = 1,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 19L,
                            Code = "system:permission:edit",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "编辑权限",
                            ParentId = 4L,
                            Sort = 2,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 20L,
                            Code = "system:permission:delete",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "删除权限",
                            ParentId = 4L,
                            Sort = 3,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 21L,
                            Code = "logs:operation:query",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查询操作日志",
                            ParentId = 6L,
                            Sort = 0,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 22L,
                            Code = "logs:operation:delete",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "删除操作日志",
                            ParentId = 6L,
                            Sort = 1,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 23L,
                            Code = "logs:exception:query",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查询异常日志",
                            ParentId = 7L,
                            Sort = 0,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 24L,
                            Code = "logs:exception:delete",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "删除异常日志",
                            ParentId = 7L,
                            Sort = 1,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 25L,
                            Code = "system:config",
                            Component = "system/settings/index",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icon = "Tools",
                            Name = "系统设置",
                            ParentId = 1L,
                            Path = "/system/settings",
                            Sort = 4,
                            Type = (byte)0,
                            Visible = (byte)1
                        },
                        new
                        {
                            Id = 26L,
                            Code = "system:config:query",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "查询系统设置",
                            ParentId = 25L,
                            Sort = 0,
                            Type = (byte)1,
                            Visible = (byte)0
                        },
                        new
                        {
                            Id = 27L,
                            Code = "system:config:edit",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "编辑系统设置",
                            ParentId = 25L,
                            Sort = 1,
                            Type = (byte)1,
                            Visible = (byte)0
                        });
                });

            modelBuilder.Entity("ZJAdmin.Api.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("sys_role");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "super_admin",
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "系统超级管理员，拥有所有权限",
                            Name = "超级管理员"
                        });
                });

            modelBuilder.Entity("ZJAdmin.Api.Models.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("sys_role_permission");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            PermissionId = 1L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            PermissionId = 2L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            PermissionId = 3L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            PermissionId = 4L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            PermissionId = 5L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            PermissionId = 6L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            PermissionId = 7L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            PermissionId = 8L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            PermissionId = 9L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            PermissionId = 10L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            PermissionId = 11L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            PermissionId = 12L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            PermissionId = 13L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 14L,
                            PermissionId = 14L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 15L,
                            PermissionId = 15L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 16L,
                            PermissionId = 16L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 17L,
                            PermissionId = 17L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 18L,
                            PermissionId = 18L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 19L,
                            PermissionId = 19L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 20L,
                            PermissionId = 20L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 21L,
                            PermissionId = 21L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 22L,
                            PermissionId = 22L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 23L,
                            PermissionId = 23L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 24L,
                            PermissionId = 24L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 25L,
                            PermissionId = 25L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 26L,
                            PermissionId = 26L,
                            RoleId = 1L
                        },
                        new
                        {
                            Id = 27L,
                            PermissionId = 27L,
                            RoleId = 1L
                        });
                });

            modelBuilder.Entity("ZJAdmin.Api.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LockoutEndTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("LoginFailCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<byte>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("sys_user");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreateTime = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@zjadmin.com",
                            IsDeleted = (byte)0,
                            LoginFailCount = 0,
                            Nickname = "超级管理员",
                            Password = "$2a$11$6ND.tr9CxuOn1XDjNBWeJOb81Tx2D6N5IlJexHLcKtLuzuyQ4ONV6",
                            Status = (byte)1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ZJAdmin.Api.Models.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("sys_user_role");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            RoleId = 1L,
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("ZJAdmin.Api.Models.RolePermission", b =>
                {
                    b.HasOne("ZJAdmin.Api.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZJAdmin.Api.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ZJAdmin.Api.Models.UserRole", b =>
                {
                    b.HasOne("ZJAdmin.Api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZJAdmin.Api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZJAdmin.Api.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ZJAdmin.Api.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ZJAdmin.Api.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
